version: '3'
services:
  postgres:
      image: postgres:alpine
      volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
          - "5432:5432"
      environment:
          POSTGRES_PASSWORD: mypass

  go:
      build: ./docker/Go
      volumes:
          - .:/Development/projects/social-tournament-service
      working_dir: /Development/projects/social-tournament-service
      command: go run src/main.go
      links:
          - postgres:db
      ports:
          - "8080"

  proxy:
      image: nginx:latest
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./docker/Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      links:
          - go:app
